name: Install ODP Releaser
description: Install ODP releaser

runs:
  using: "composite"
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1
      with:
        enable-cache: true
        cache-dependency-glob: ""
        cache-suffix: "odp-releaser-${{ job.workflow_sha }}"
        prune-cache: false

    - name: Install ODP Releaser
      env:
        ODP_RELEASER_REF: ${{ job.workflow_sha }}
      run:
        uv tool install
        git+https://github.com/gulfofmaine/odp-releaser.git@${ODP_RELEASER_REF}
